In [9]:
import requests
import defs

In [10]:
session = requests.Session()

In [11]:
instrument = "EUR_USD"
count = 10
granularity = "H1"

In [12]:
url = f"{defs.OANDA_URL}/instruments/{instrument}/candles"
params  = dict(count=count, granularity=granularity, price = "MBA")
response = session.get(url, headers=defs.SECURE_HEADER, params=params)

In [13]:
response.status_code

200

In [14]:
data=response.json()

In [16]:
data.keys()

dict_keys(['instrument', 'granularity', 'candles'])

In [17]:
len(data["candles"])

10

In [18]:
for candle in data["candles"]:
    print(candle)

{'complete': True, 'volume': 6152, 'time': '2024-07-18T07:00:00.000000000Z', 'bid': {'o': '1.09304', 'h': '1.09344', 'l': '1.09254', 'c': '1.09308'}, 'mid': {'o': '1.09312', 'h': '1.09352', 'l': '1.09262', 'c': '1.09315'}, 'ask': {'o': '1.09320', 'h': '1.09361', 'l': '1.09269', 'c': '1.09322'}}
{'complete': True, 'volume': 4078, 'time': '2024-07-18T08:00:00.000000000Z', 'bid': {'o': '1.09306', 'h': '1.09381', 'l': '1.09282', 'c': '1.09300'}, 'mid': {'o': '1.09314', 'h': '1.09389', 'l': '1.09290', 'c': '1.09308'}, 'ask': {'o': '1.09322', 'h': '1.09397', 'l': '1.09298', 'c': '1.09315'}}
{'complete': True, 'volume': 2750, 'time': '2024-07-18T09:00:00.000000000Z', 'bid': {'o': '1.09299', 'h': '1.09310', 'l': '1.09265', 'c': '1.09303'}, 'mid': {'o': '1.09307', 'h': '1.09318', 'l': '1.09272', 'c': '1.09310'}, 'ask': {'o': '1.09315', 'h': '1.09325', 'l': '1.09280', 'c': '1.09317'}}
{'complete': True, 'volume': 2820, 'time': '2024-07-18T10:00:00.000000000Z', 'bid': {'o': '1.09301', 'h': '1.09356', 'l': '1.09279', 'c': '1.09323'}, 'mid': {'o': '1.09308', 'h': '1.09363', 'l': '1.09286', 'c': '1.09330'}, 'ask': {'o': '1.09316', 'h': '1.09370', 'l': '1.09294', 'c': '1.09338'}}
{'complete': True, 'volume': 2832, 'time': '2024-07-18T11:00:00.000000000Z', 'bid': {'o': '1.09321', 'h': '1.09325', 'l': '1.09255', 'c': '1.09269'}, 'mid': {'o': '1.09329', 'h': '1.09332', 'l': '1.09263', 'c': '1.09276'}, 'ask': {'o': '1.09337', 'h': '1.09340', 'l': '1.09270', 'c': '1.09283'}}
{'complete': True, 'volume': 6925, 'time': '2024-07-18T12:00:00.000000000Z', 'bid': {'o': '1.09268', 'h': '1.09362', 'l': '1.09231', 'c': '1.09278'}, 'mid': {'o': '1.09276', 'h': '1.09370', 'l': '1.09238', 'c': '1.09285'}, 'ask': {'o': '1.09284', 'h': '1.09379', 'l': '1.09245', 'c': '1.09292'}}
{'complete': True, 'volume': 7760, 'time': '2024-07-18T13:00:00.000000000Z', 'bid': {'o': '1.09277', 'h': '1.09284', 'l': '1.09065', 'c': '1.09107'}, 'mid': {'o': '1.09284', 'h': '1.09291', 'l': '1.09073', 'c': '1.09114'}, 'ask': {'o': '1.09292', 'h': '1.09299', 'l': '1.09081', 'c': '1.09121'}}
{'complete': True, 'volume': 7103, 'time': '2024-07-18T14:00:00.000000000Z', 'bid': {'o': '1.09108', 'h': '1.09160', 'l': '1.09042', 'c': '1.09141'}, 'mid': {'o': '1.09115', 'h': '1.09167', 'l': '1.09050', 'c': '1.09148'}, 'ask': {'o': '1.09122', 'h': '1.09175', 'l': '1.09058', 'c': '1.09155'}}
{'complete': True, 'volume': 6246, 'time': '2024-07-18T15:00:00.000000000Z', 'bid': {'o': '1.09139', 'h': '1.09177', 'l': '1.09043', 'c': '1.09114'}, 'mid': {'o': '1.09146', 'h': '1.09184', 'l': '1.09051', 'c': '1.09122'}, 'ask': {'o': '1.09153', 'h': '1.09192', 'l': '1.09059', 'c': '1.09130'}}
{'complete': False, 'volume': 5040, 'time': '2024-07-18T16:00:00.000000000Z', 'bid': {'o': '1.09115', 'h': '1.09155', 'l': '1.09103', 'c': '1.09147'}, 'mid': {'o': '1.09122', 'h': '1.09163', 'l': '1.09111', 'c': '1.09154'}, 'ask': {'o': '1.09129', 'h': '1.09171', 'l': '1.09119', 'c': '1.09161'}}

In [19]:
prices = ["mid", "bid", "ask"]
ohlc= ["o", "h", "l", "c"]
for price in prices:
    for oh in ohlc:
        print(f"{price}_{oh}")

mid_o
mid_h
mid_l
mid_c
bid_o
bid_h
bid_l
bid_c
ask_o
ask_h
ask_l
ask_c

In [20]:
data["candles"][0]

{'complete': True,
 'volume': 6152,
 'time': '2024-07-18T07:00:00.000000000Z',
 'bid': {'o': '1.09304', 'h': '1.09344', 'l': '1.09254', 'c': '1.09308'},
 'mid': {'o': '1.09312', 'h': '1.09352', 'l': '1.09262', 'c': '1.09315'},
 'ask': {'o': '1.09320', 'h': '1.09361', 'l': '1.09269', 'c': '1.09322'}}

In [24]:
our_data = []
for candle in data["candles"]:
    if candle["complete"]==False:
        continue
    new_dict = {}
    new_dict["time"] = candle["time"]
    new_dict["volume"] = candle["volume"]
    for price in prices:
        for oh in ohlc:
            new_dict[f"{price}_{oh}"] = candle[price][oh]
    our_data.append(new_dict)
print(our_data)

[{'time': '2024-07-18T07:00:00.000000000Z', 'volume': 6152, 'mid_o': '1.09312', 'mid_h': '1.09352', 'mid_l': '1.09262', 'mid_c': '1.09315', 'bid_o': '1.09304', 'bid_h': '1.09344', 'bid_l': '1.09254', 'bid_c': '1.09308', 'ask_o': '1.09320', 'ask_h': '1.09361', 'ask_l': '1.09269', 'ask_c': '1.09322'}, {'time': '2024-07-18T08:00:00.000000000Z', 'volume': 4078, 'mid_o': '1.09314', 'mid_h': '1.09389', 'mid_l': '1.09290', 'mid_c': '1.09308', 'bid_o': '1.09306', 'bid_h': '1.09381', 'bid_l': '1.09282', 'bid_c': '1.09300', 'ask_o': '1.09322', 'ask_h': '1.09397', 'ask_l': '1.09298', 'ask_c': '1.09315'}, {'time': '2024-07-18T09:00:00.000000000Z', 'volume': 2750, 'mid_o': '1.09307', 'mid_h': '1.09318', 'mid_l': '1.09272', 'mid_c': '1.09310', 'bid_o': '1.09299', 'bid_h': '1.09310', 'bid_l': '1.09265', 'bid_c': '1.09303', 'ask_o': '1.09315', 'ask_h': '1.09325', 'ask_l': '1.09280', 'ask_c': '1.09317'}, {'time': '2024-07-18T10:00:00.000000000Z', 'volume': 2820, 'mid_o': '1.09308', 'mid_h': '1.09363', 'mid_l': '1.09286', 'mid_c': '1.09330', 'bid_o': '1.09301', 'bid_h': '1.09356', 'bid_l': '1.09279', 'bid_c': '1.09323', 'ask_o': '1.09316', 'ask_h': '1.09370', 'ask_l': '1.09294', 'ask_c': '1.09338'}, {'time': '2024-07-18T11:00:00.000000000Z', 'volume': 2832, 'mid_o': '1.09329', 'mid_h': '1.09332', 'mid_l': '1.09263', 'mid_c': '1.09276', 'bid_o': '1.09321', 'bid_h': '1.09325', 'bid_l': '1.09255', 'bid_c': '1.09269', 'ask_o': '1.09337', 'ask_h': '1.09340', 'ask_l': '1.09270', 'ask_c': '1.09283'}, {'time': '2024-07-18T12:00:00.000000000Z', 'volume': 6925, 'mid_o': '1.09276', 'mid_h': '1.09370', 'mid_l': '1.09238', 'mid_c': '1.09285', 'bid_o': '1.09268', 'bid_h': '1.09362', 'bid_l': '1.09231', 'bid_c': '1.09278', 'ask_o': '1.09284', 'ask_h': '1.09379', 'ask_l': '1.09245', 'ask_c': '1.09292'}, {'time': '2024-07-18T13:00:00.000000000Z', 'volume': 7760, 'mid_o': '1.09284', 'mid_h': '1.09291', 'mid_l': '1.09073', 'mid_c': '1.09114', 'bid_o': '1.09277', 'bid_h': '1.09284', 'bid_l': '1.09065', 'bid_c': '1.09107', 'ask_o': '1.09292', 'ask_h': '1.09299', 'ask_l': '1.09081', 'ask_c': '1.09121'}, {'time': '2024-07-18T14:00:00.000000000Z', 'volume': 7103, 'mid_o': '1.09115', 'mid_h': '1.09167', 'mid_l': '1.09050', 'mid_c': '1.09148', 'bid_o': '1.09108', 'bid_h': '1.09160', 'bid_l': '1.09042', 'bid_c': '1.09141', 'ask_o': '1.09122', 'ask_h': '1.09175', 'ask_l': '1.09058', 'ask_c': '1.09155'}, {'time': '2024-07-18T15:00:00.000000000Z', 'volume': 6246, 'mid_o': '1.09146', 'mid_h': '1.09184', 'mid_l': '1.09051', 'mid_c': '1.09122', 'bid_o': '1.09139', 'bid_h': '1.09177', 'bid_l': '1.09043', 'bid_c': '1.09114', 'ask_o': '1.09153', 'ask_h': '1.09192', 'ask_l': '1.09059', 'ask_c': '1.09130'}]

In [25]:
candles_df=pd.DataFrame(our_data)

In [26]:
candles_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2024-07-18T07:00:00.000000000Z,6152,1.09312,1.09352,1.09262,1.09315,1.09304,1.09344,1.09254,1.09308,1.09320,1.09361,1.09269,1.09322
1,2024-07-18T08:00:00.000000000Z,4078,1.09314,1.09389,1.09290,1.09308,1.09306,1.09381,1.09282,1.09300,1.09322,1.09397,1.09298,1.09315
2,2024-07-18T09:00:00.000000000Z,2750,1.09307,1.09318,1.09272,1.09310,1.09299,1.09310,1.09265,1.09303,1.09315,1.09325,1.09280,1.09317
3,2024-07-18T10:00:00.000000000Z,2820,1.09308,1.09363,1.09286,1.09330,1.09301,1.09356,1.09279,1.09323,1.09316,1.09370,1.09294,1.09338
4,2024-07-18T11:00:00.000000000Z,2832,1.09329,1.09332,1.09263,1.09276,1.09321,1.09325,1.09255,1.09269,1.09337,1.09340,1.09270,1.09283
5,2024-07-18T12:00:00.000000000Z,6925,1.09276,1.09370,1.09238,1.09285,1.09268,1.09362,1.09231,1.09278,1.09284,1.09379,1.09245,1.09292
6,2024-07-18T13:00:00.000000000Z,7760,1.09284,1.09291,1.09073,1.09114,1.09277,1.09284,1.09065,1.09107,1.09292,1.09299,1.09081,1.09121
7,2024-07-18T14:00:00.000000000Z,7103,1.09115,1.09167,1.09050,1.09148,1.09108,1.09160,1.09042,1.09141,1.09122,1.09175,1.09058,1.09155
8,2024-07-18T15:00:00.000000000Z,6246,1.09146,1.09184,1.09051,1.09122,1.09139,1.09177,1.09043,1.09114,1.09153,1.09192,1.09059,1.09130

In [27]:
candles_df.to_pickle("eur_usd_h1.pkl")

In [29]:
test_df = pd.read_pickle("eur_usd_h1.pkl")

In [30]:
test_df

,time,volume,mid_o,mid_h,mid_l,mid_c,bid_o,bid_h,bid_l,bid_c,ask_o,ask_h,ask_l,ask_c
0,2024-07-18T07:00:00.000000000Z,6152,1.09312,1.09352,1.09262,1.09315,1.09304,1.09344,1.09254,1.09308,1.09320,1.09361,1.09269,1.09322
1,2024-07-18T08:00:00.000000000Z,4078,1.09314,1.09389,1.09290,1.09308,1.09306,1.09381,1.09282,1.09300,1.09322,1.09397,1.09298,1.09315
2,2024-07-18T09:00:00.000000000Z,2750,1.09307,1.09318,1.09272,1.09310,1.09299,1.09310,1.09265,1.09303,1.09315,1.09325,1.09280,1.09317
3,2024-07-18T10:00:00.000000000Z,2820,1.09308,1.09363,1.09286,1.09330,1.09301,1.09356,1.09279,1.09323,1.09316,1.09370,1.09294,1.09338
4,2024-07-18T11:00:00.000000000Z,2832,1.09329,1.09332,1.09263,1.09276,1.09321,1.09325,1.09255,1.09269,1.09337,1.09340,1.09270,1.09283
5,2024-07-18T12:00:00.000000000Z,6925,1.09276,1.09370,1.09238,1.09285,1.09268,1.09362,1.09231,1.09278,1.09284,1.09379,1.09245,1.09292
6,2024-07-18T13:00:00.000000000Z,7760,1.09284,1.09291,1.09073,1.09114,1.09277,1.09284,1.09065,1.09107,1.09292,1.09299,1.09081,1.09121
7,2024-07-18T14:00:00.000000000Z,7103,1.09115,1.09167,1.09050,1.09148,1.09108,1.09160,1.09042,1.09141,1.09122,1.09175,1.09058,1.09155
8,2024-07-18T15:00:00.000000000Z,6246,1.09146,1.09184,1.09051,1.09122,1.09139,1.09177,1.09043,1.09114,1.09153,1.09192,1.09059,1.09130